printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'all'
bracketSpacing: false
jsxBracketSameLine: false
arrowParens: 'avoid'
proseWrap: 'preserve'
endOfLine: 'lf'
