version: 2.1
jobs:
    build:
        docker:
            - image: satantime/puppeteer-node:12-buster
        steps:
            - checkout
            - restore_cache:
                  key: root-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: NPM Install
                  command: npm install

            - save_cache:
                  key: root-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Lint
                  command: npm run lint
            - run:
                  name: Tests
                  command: npm run test -- --code-coverage
            - run:
                  name: Collecting Coverage
                  command: ./node_modules/coveralls/bin/coveralls.js < test-reports/coverage/lcov.info
            - store_test_results:
                  path: ./test-reports
            - store_artifacts:
                  path: ./test-reports/coverage
                  prefix: coverage
